### ISSUE TITLE
ユーザーは付箋の情報を永続化したい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#1]
受け入れ条件
- [x] ページをリロードしても付箋の情報が残っていること

Point:5

**Comment by theMistletoe** [comment]
他の人と共有できる必要ない
自分のブラウザで保存できれば良い

おそらくLocalStorageでの実装が使い勝手良い

**Comment by theMistletoe** [comment]
付箋の情報を"store"を使った実装にする

**Comment by rtkn586** [comment]
タスク分割

- [ ] vuex-persistedstateをインストール
- [ ] https://mebee.info/2019/12/25/post-4710/　このページ通りにファイル作成する
- [ ] タスクをstoreで管理する
- [ ] storeで管理しているタスクをリロードした際に表示する
