### ISSUE TITLE
ユーザーはTODOを続けて追加したい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#15]
- [x] エンターキーで追加できるようにしたい
- [x] 付箋追加後、入力していたテキストをクリアして次の付箋を入力できる
 
Point:2

**Comment by theMistletoe** [comment]
ポイント:2

**Comment by rtkn586** [comment]
タスク分割

- [ ] エンターキーを押したときの処理を追加する
- [ ] タスクの追加後にテキストボックスにフォーカスをあてる
