### ISSUE TITLE
お披露目会の準備

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#21]
### お披露目会の簡単なアジェンダ

- TODO開発の概要、ゴールのご説明（takahashi）
- 開発のすすめ方、スプリントの概要 (watanabe-san)
  - ふりかえりこんな感じですすめました
  - ポインティングをしました etc
- TODOアプリのデモ（開発メンバー）
- コンフルのドキュメントベースで以下のお話？（開発メンバー）
  - 開発の中で工夫した, 学んだ点
  - 今後に活かせる点 ( indexページ、working agreementの話)
- まとめ（tanaka-san）

Point:3

**Comment by theMistletoe** [comment]
進め方
何を話すか
作ったものだけだと「そっか」ってなるし

開発とか成長の軌跡を終えるようにしたい

**Comment by theMistletoe** [comment]
シナリオを考えましょう！

**Comment by theMistletoe** [comment]
ScM的にも感じたこととかあれば

**Comment by theMistletoe** [comment]
to:アジャイルチームメンバーくらい

**Comment by theMistletoe** [comment]
お披露目会の資料準備について

https://docs.google.com/presentation/d/1NvAadsQy5nqmU06_pyvtvIc5JPAtTCtKCnRHxnSVUC8/edit?usp=sharing

スライド上記で行きたいと思います。

ページとそれぞれ割り振りについてここに整理します。

全体ファシ田中でしますので、
p1~p2田中(1分)
p3~p5(5分)
p6~p9(5分)
P10~P11(15分質問込み)
p12(2分)
合計30分内

くらいを見込みで思っています。

**Comment by theMistletoe** [comment]
Dev二人は軽くリハして確認したので大丈夫そうです！
10m以内には終わりそうな感じかと思います。5分質問かな。
