### ISSUE TITLE
ユーザーはTODOを編集したい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#4]
受け入れ条件
- [x] 一覧から付箋のタイトルを編集できること
- [x] 詳細画面から付箋のタイトルと説明を編集できること

Point:5

**Comment by theMistletoe** [comment]
編集の確定：Focusout or press enter

**Comment by theMistletoe** [comment]
付箋をクリックすると詳細画面にいける必要もあるので、
修正したい場合、詳細画面にいきたい場合でわかりやすいようにする

**Comment by theMistletoe** [comment]
詳細画面に関してはすぐ編集できるような状態になっていても良いかも

**Comment by rtkn586** [comment]
タスク分割

- [ ] 一覧画面から詳細画面に遷移する方法をタイトルからのリンク→ボタンに変更
- [ ] 一覧画面のタイトルをクリックしたときに編集状態にする
- [ ] 一覧画面のタイトル編集時にフォーカスを外すか、エンターキーを押したときに編集を完了させる
- [ ] 詳細画面でタイトルと説明を編集できるようにする
