### ISSUE TITLE
ユーザーはTODOを削除したい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#5]
受け入れ条件
- [x] 一覧から付箋を削除できること
- [x] 編集画面から付箋を削除できること

Point:3

**Comment by theMistletoe** [comment]
詳細画面から削除した場合は一覧画面に戻れる

**Comment by rtkn586** [comment]
タスク分割

- [ ] 一覧画面に削除ボタンを作成する
- [ ] 一覧画面の削除ボタンを押したときにタスクを消すアクションを追加する
- [ ] 詳細画面に削除ボタンを作成する
- [ ]  詳細画面の削除ボタンを押したときにタスクを消して、一覧画面に戻るアクションを追加する
