### ISSUE TITLE
ユーザーはTODOの詳細を確認したい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#6]
何故なら詳細画面でタイトルと説明を編集したいから
説明はテキストエリアで長文を残したい

受け入れ条件
- [x] 詳細画面が表示できること
- [x] タイトルと説明が見れること
- [x] 詳細画面から一覧画面に戻れること

Point:3

**Comment by theMistletoe** [comment]
一覧画面には詳細文は見えない？

**Comment by rtkn586** [comment]
タスク分割

- [ ] 付箋のオブジェクトに詳細を追加する
- [ ] 詳細画面を作成する
- [ ] 詳細画面に遷移するリンクを作成する
- [ ] 一覧画面のタスクタイトルと詳細画面のタスクタイトルを紐づける
- [ ] 
- [ ]

**Comment by rtkn586** [comment]
（新）
- [ ] タスク一覧とタスク詳細のコンポーネントを作成する
- [ ] state項目を追加する
- [ ] 表示するコンポーネントをクリックで切り替えられるようにする
