### ISSUE TITLE
ユーザーはTODOの詳細ページのパーマネントリンクがほしい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#7]
何故なら付箋のリンクを自分の作業ログに貼り付けたいから

受け入れ条件
- [x] 付箋詳細のパーマネントリンクが作成できること

Point:5

**Comment by toshipon** [comment]
nuxtのルーティング機能を利用して実現
https://ja.nuxtjs.org/guide/routing/

**Comment by theMistletoe** [comment]
今はIndex.vueだけ
pages配下にファイルを作るとURLが作られる

**Comment by theMistletoe** [comment]
ページ間でどのようにデータを集約するなが鍵

**Comment by theMistletoe** [comment]
URLはDevで決めてしまってよし

**Comment by theMistletoe** [comment]
付箋いっこいっこに対してURLができる？

**Comment by rtkn586** [comment]
タスク分割

- [ ] storeディレクトリにlocalStorageとのデータの受け渡しを配置する
- [ ] ディレクトリ構成を動的ルーティングができるように変更する
https://qiita.com/tekondo/items/80555991c019808669ef
