### ISSUE TITLE
ユーザーはTODOの一覧で付箋の並べ替えをしたい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#8]
何故ならTODOの付箋の優先度によって並び替えをしたいから

受け入れ条件
- [x] 付箋の並び替えができること
- [x] 並び替えた結果が永続化されること(ブラウザに)

Point:5

**Comment by theMistletoe** [comment]
並び替え方法

ドラッグ？何かボタン？
→ドラッグアンドドロップ

難しかったら相談
例えば上下移動させるボタンがあるとか

もしくはライブラリを使ったり（ドラガブル？）
今までプラグインの導入のタスクがなかったので、それの機会にしたい

難易度に応じて応相談

**Comment by rtkn586** [comment]
タスク分割

- [ ] Vue.Draggableをインストールする
- [ ]<draggable>タグを設定する
https://www.ritolab.com/entry/173
