### ISSUE TITLE
tailwindcss を使ってレイアウトを整えたい

### ISSUE THREAD

**Issue by toshipon** [theMistletoe/TODO-Practice#9]
CSSのレイアウトを tailwindcssというライブラリを使って整えたいので
導入していきたい

**Comment by toshipon** [comment]
受け入れ条件
- [ ] 今スプリントで作成するコンポーネントにtailwindcssが適用されていること

**Comment by rtkn586** [comment]
タスク分割
- [ ] tailwindcssをvscodeに導入する
- [ ] tailwindcssを適用する箇所を決めて実装する
